name: Build octofetch

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  style:
    name: Check styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      name: Checkout
        
      - uses: actions-rs/toolchain@v1
      name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
          
      - uses: actions-rs/cargo@v1
      name: cargo fmt --check
        with:
          command: fmt
          args: --all -- --check
            
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        name: Install Rust
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions/checkout@v2
        name: Build
        run: cargo build --verbose --release;cp target/release/octofetch .    
      - name: Run tests
        run: cargo test --verbose --release
      - uses: actions/upload-artifact@v1
        name: Upload artifact
        with:
          name: Build artifact
          path: octofetch
                    